# Generated by Django 5.1.2 on 2024-10-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralServerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='updatedAt',
            field=models.DateField(auto_now=True),
        ),
    ]
