# Generated by Django 5.1.2 on 2024-10-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentralServerapp', '0002_alter_license_createdat_alter_license_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='deviceNo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
